project:
  type: website

website:
  description: "A blog built with Quarto and filled with AI-generated slop."
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "domestik"
  navbar:
    right:
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css



